parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\Behat\:
            resource: '../tests/Behat/*'

        App\Tests\Behat\AppContext:
            arguments:
                $managerRegistry: "@doctrine"
                $iriConverter: "@api_platform.symfony.iri_converter"